server:
  port:
    8888
spring:
  application:
    name: ai-agent
  ai:
    ollama:
      base-url: http://192.168.0.14:11434
      chat:
        model: qwen3:32b

gitlab:
  url: https://192.168.0.59:19443/
